apiVersion: v1
kind: Service
metadata:
  resourceVersion: "1.0"
  name: calibre-web-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8083
  selector:
    app: calibre-web