apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: hermes-services
spec:
  ports:
  - name: https-iredmail
    port: 443
    targetPort: 443
  - name: smtps
    port: 587
    targetPort: 587
  selector:
    app: hermes