apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: hermes-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 34.175.159.251
  selector:
    app: hermes
  ports:
  - name: https-iredmail
    port: 443
    targetPort: 443
  - name: smtps
    port: 587
    targetPort: 587
