apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apollo-ingress 
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  rules:
  - host: redmine.apollo.olympus
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name : apollo-nodeport
            port :
              number: 3000

  - host: calibre.apollo.olympus
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name : apollo-nodeport
            port :
              number: 8083