apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      labels:
        app: apollo
    spec:

      containers:
####### MySQL

      - name: mysql
        image: mysql:5.7-debian
        
        ports:
        - containerPort: 3306

        resources:
         limits:
            memory: "512Mi"
            cpu: "25m"

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: apollo-secrets
              key: mysql-root-password
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: apollo-secrets
              key: mysql-password
              
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
          subPath: mysql
          
        - name: mysql-config
          mountPath: /etc/mysql/mysql.cnf
          subPath: mysql.cnf

        - name: apollo-backups
          mountPath: /backups

####### Redmine

      - name: redmine
        image: asofainy/redmine:v1.1.0
        imagePullPolicy: Always        

        env:
        - name: RAILS_ENV
          value: production

        ports:
        - containerPort: 3000

        resources:
         limits:
            memory: "512Mi"
            cpu: "100m"

#        securityContext:
#          privileged: true 

        volumeMounts:      
        - name: redmine-config
          mountPath: /usr/src/redmine/config/configuration.yml
          subPath: configuration.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/database.yml
          subPath: database.yml
        - name: redmine-config       
          mountPath: /usr/src/redmine/config/settings.yml
          subPath: settings.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/application.rb
          subPath: application.rb
        - name: redmine-config
          mountPath: /config/env.yml
          subPath: env.yml
        - name: redmine-config
          mountPath: /etc/ImageMagick-6/policy.xml
          subPath: policy.xml
# A Verifier si le pod ne demarre pas
        - name: redmine-files
          mountPath: /usr/src/redmine/files
          subPath: files
        - name: redmine-files
          mountPath: /usr/src/redmine/file_index
          subPath: file_index

        - name: redmine-repo
          mountPath: /repositories

        - name: library
          mountPath: /library

        - name: apollo-backups
          mountPath: /backups

#        - name: mysql-config
#          mountPath: /mnt/etc/mysql
#        - name: mysql-restore
#          mountPath: /mnt/var/lib/mysql


####### Calibre Web


      - name: calibre-web
        image: asofainy/calibre-web:v1.0.0
        imagePullPolicy: Always

        env:

          - name:  FLASK_DEBUG
            value: "1"

          - name:  CALIBRE_DBPATH
            value: /opt/calibre-web

        ports:
        - containerPort: 8083

        resources:
         limits:
            memory: "512Mi"
            cpu: "25m"

        volumeMounts:

#        - name: calibre-web-data
#          mountPath: /opt/calibre-web
#          subPath: calibre-web
        
#        - name: calibre-web-data
#          mountPath: /opt/calibre
#          subPath: calibre

        - name: library
          mountPath: /library

        - name: apollo-backups
          mountPath: /backups
          
###### Volumes

      volumes:

        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc 

        - name: mysql-config
          configMap:
            name: mysql-config

        - name: redmine-repo
          persistentVolumeClaim:
            claimName: redmine-repo-pvc

        - name: redmine-config
          configMap:
            name: redmine-config

        - name: redmine-files
          persistentVolumeClaim:
            claimName: redmine-files-pvc

        - name: calibre-web-data
          persistentVolumeClaim:
            claimName: calibre-web-data-pvc
        
        - name: library
          persistentVolumeClaim:
            claimName: library-pvc

        - name: apollo-backups
          persistentVolumeClaim:
            claimName: apollo-backups-pvc   
