apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      labels:
        app: apollo
    spec:
      containers:
      - name: mysql
        image: mysql:5.7-debian
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: My5QL_p@55

        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
          subPath: mysqld.cnf
        - name: backup
          mountPath: /backup
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100m"

      - name: redmine
        image: asofainy/redmine:v1.1.0
        imagePullPolicy: Always        

        env:
        - name: RAILS_ENV
          value: production
        ports:
        - containerPort: 3000

        securityContext:
          privileged: true 
        volumeMounts:
        - name: redmine-config
          mountPath: /usr/src/redmine/config/configuration.yml
          subPath: configuration.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/database.yml
          subPath: database.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/settings.yml
          subPath: settings.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/application.rb
          subPath: application.rb
        - name: redmine-config
          mountPath: /config/env.yml
          subPath: env.yml
        - name: redmine-config
          mountPath: /etc/ImageMagick-6/policy.xml
          subPath: policy.xml
# A Verifier si le pod ne demarre pas
        - name: redmine-files
          mountPath: /usr/src/redmine/files
        - name: redmine-repo
          mountPath: /repositories
        - name: library
          mountPath: /library
        - name: mysql-data
          mountPath: /mnt/var/lib/mysql
        - name: mysql-config
          mountPath: /mnt/etc/mysql

        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "700Mi"
            cpu: "250m"

      - name: calibre-web
        image: debian:11.5
        imagePullPolicy: IfNotPresent
        env:
          - name: CALIBRE_VERSION
            value: 6.7.1
          - name: CALIBRE_WEB_VERSION
            value: 0.6.12
          - name: FLASK_DEBUG
            value: "1"
          - name: CALIBRE_DBPATH
            value: /opt/calibre-web
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: apollo-secrets
                key: github-token
        command: ["/bin/bash","-c"]
        args: 
          - apt-get -qqq update && apt-get -qqq  install -y git | sed -u "s/.*/` printf "calibre-web  |" ` &/" ;
            git clone -b build --progress https://${GITHUB_TOKEN}@github.com/asofainy/calibre-web.git /tmp/calibre-web | sed -u "s/.*/` printf "calibre-web  |" ` &/" ;
            chmod -R +x /tmp/calibre-web/run/install.sh && /tmp/calibre-web/run/install.sh | sed -u "s/.*/` printf "calibre-web  |" ` &/" ;         

        ports:
        - containerPort: 8083
        volumeMounts:
        - name: library
          mountPath: /library
        - name: calibre-data
          mountPath: /opt

        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100m"

      volumes:
        - name: redmine-repo
          persistentVolumeClaim:
            claimName: redmine-repo-pvc
        - name: library
          persistentVolumeClaim:
            claimName: library-pvc
        - name: backup
          persistentVolumeClaim:
            claimName: backup-pvc
        - name: redmine-config
          configMap:
            name: redmine-config
        - name: redmine-files
          persistentVolumeClaim:
            claimName: redmine-files-pvc
        - name: calibre-data
          persistentVolumeClaim:
            claimName: calibre-data-pvc
        - name: calibre-web-data
          persistentVolumeClaim:
            claimName: calibre-web-data-pvc
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
        - name: mysql-config
          configMap:
            name: mysql-config

