apiVersion: v1
kind: Service
metadata:
  name: apollo-services
spec:
  selector:
    app: apollo
  ports:
  - name: https-redmine
    port: 3443
    targetPort: 3443
  - name: https-calibre
    port: 8083
    targetPort: 8083
  - name: mysql
    port: 3306
    targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: apollo-nodeport
spec:
  type: NodePort
  selector:
    app: apollo
  ports:
  - name: https-redmine
    port: 3443
    targetPort: 3443
  - name: https-calibre
    port: 8083
    targetPort: 8083