apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      labels:
        app: apollo
    spec:

      containers:
####### MySQL

      - name: mysql
        image: mysql:5.7-debian
        
        ports:
        - containerPort: 3306

        resources:
          limits:
            memory: "200Mi"
            cpu: "25m"

        readinessProbe:        
          initialDelaySeconds: 30
          periodSeconds: 30
          exec:
            command:
            - bash
            - -c
            - mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD ping &> /dev/null

        livenessProbe:        
          initialDelaySeconds: 60
          periodSeconds: 300
          exec:
            command:
            - bash
            - -c
            - mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD ping &> /dev/null


        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: apollo-secrets
              key: mysql-root-password
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: apollo-secrets
              key: mysql-password
              
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
          subPath: mysql
          
        - name: mysql-config
          mountPath: /etc/mysql/mysql.cnf
          subPath: mysql.cnf

        - name: apollo-backups
          mountPath: /backups

        - name: calibre-web-data
          mountPath: /mnt/opt  
        
      
####### Redmine

      - name: redmine
        image: asofainy/redmine:v1.2.0
#        imagePullPolicy: Always        

        env:
        - name: RAILS_ENV
          value: production
        - name: HTTPS_PORT
          value: "3443"

        ports:
        - name: https-redmine
          containerPort: 3443

        resources:
         limits:
            memory: "500Mi"
            cpu: "100m"

        readinessProbe:        
          initialDelaySeconds: 900
          periodSeconds: 60
          httpGet:
            scheme: HTTPS
            path: /
            port: 3443    

        livenessProbe:        
          initialDelaySeconds: 300
          periodSeconds: 300
          httpGet:
            scheme: HTTPS 
            path: /
            port: 3443

#        securityContext:
#          privileged: true 

        volumeMounts:      
        - name: redmine-config
          mountPath: /usr/src/redmine/config/configuration.yml
          subPath: configuration.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/database.yml
          subPath: database.yml
        - name: redmine-config       
          mountPath: /usr/src/redmine/config/settings.yml
          subPath: settings.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/application.rb
          subPath: application.rb
        - name: redmine-config
          mountPath: /usr/src/redmine/Gemfile
          subPath: Gemfile
        - name: redmine-config
          mountPath: /etc/ImageMagick-6/policy.xml
          subPath: policy.xml
# A Verifier si le pod ne demarre pas
        - name: redmine-files
          mountPath: /usr/src/redmine/files
          subPath: files
        - name: redmine-files
          mountPath: /usr/src/redmine/file_index
          subPath: file_index

        - name: redmine-repo
          mountPath: /repositories

        - name: library
          mountPath: /library

        - name: apollo-backups
          mountPath: /backups

        - name: redmine-ssl
          mountPath: /usr/src/redmine/ssl
          readOnly: true

#        - name: mysql-config
#          mountPath: /mnt/etc/mysql
#        - name: mysql-restore
#          mountPath: /mnt/var/lib/mysql


####### Calibre Web

      - name: calibre-web
        image: asofainy/calibre-web:v1.0.0
#        imagePullPolicy: Always

        env:
          - name:  FLASK_DEBUG
            value: "1"
          - name:  CALIBRE_DBPATH
            value: /opt/calibre-web

        ports:
        - name: https-calibre
          containerPort: 8083

        resources:
          limits:
            memory: "200Mi"
            cpu: "50m"

        readinessProbe:        
          initialDelaySeconds: 120
          periodSeconds: 60
          httpGet:
            scheme: HTTPS
            path: /
            port: 8083

        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 300
          httpGet:
            scheme: HTTPS
            path: /
            port: 8083


        volumeMounts:

        - name: library
          mountPath: /library

        - name: apollo-backups
          mountPath: /backups

        - name: calibre-web-data
          mountPath: /opt/calibre-web/app.db
          subPath: calibre-web/app.db

        - name: calibre-web-ssl
          mountPath: /opt/calibre-web/ssl
          readOnly: true
       

      volumes:

        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc 

        - name: mysql-config
          configMap:
            name: mysql-config

        - name: redmine-repo
          persistentVolumeClaim:
            claimName: redmine-repo-pvc

        - name: redmine-config
          configMap:
            name: redmine-config

        - name: redmine-files
          persistentVolumeClaim:
            claimName: redmine-files-pvc

        - name: calibre-web-data
          persistentVolumeClaim:
            claimName: calibre-web-data-pvc
        
        - name: library
          persistentVolumeClaim:
            claimName: library-pvc

        - name: apollo-backups
          persistentVolumeClaim:
            claimName: apollo-backups-pvc   

        - name: redmine-ssl
          secret:
            secretName: redmine-secrets

        - name: calibre-web-ssl
          secret:
            secretName: calibre-web-secrets