apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-data-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Ki
