apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: calibre-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      namespace: production
      labels:
        app: calibre-web
    spec:
      containers:
      - name: calibre-web
        image: asofainy/calibre-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: books
          mountPath: /books
      volumes:
        - name: calibre-web-data
          persistentVolumeClaim:
            claimName: calibre-web-data-pvc
        - name: books
          persistentVolumeClaim:
            claimName: books-pvc
