apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-config
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
