apiVersion: apps/v1
kind: Deployment
metadata:
  name: helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helper
  template:
    metadata:
      labels:
        app: helper
    spec:
      containers:
      - name: helper
        image: debian:10
        command:
              - tail
              - -f
              - /dev/null
        volumeMounts:
        - name: mysql-config
          mountPath: /mnt/mysql-config
        - name: redmine-data
          mountPath: /mnt/redmine-data
        - name: redmine-repo
          mountPath: /mnt/redmine-repositories
      volumes:
        - name: mysql-config
          persistentVolumeClaim:
            claimName: mysql-pvc-config
        - name: redmine-data
          persistentVolumeClaim:
            claimName: redmine-data-pvc
        - name: redmine-repo
          persistentVolumeClaim:
            claimName: redmine-repo-pvc
