apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      namespace: production
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: asofainy/redmine:latest
        imagePullPolicy: Always
        env:
        - name: RAILS_ENV
          value: production
        - name: REDMINE_DB_MYSQL
          value: mysql.default.svc.cluster.local
        - name: REDMINE_DB_PORT
          value: '3306'
        - name: REDMINE_DB_USERNAME
          value: redmine
        - name: REDMINE_DB_PASSWORD
          value: my_password
        - name: REDMINE_DB_DATABASE
          value: redmine_production
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: redmine-config
          mountPath: /usr/src/redmine/config/configuration.yml
          subPath: configuration.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/database.yml
          subPath: database.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/settings.yml
          subPath: settings.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/application.rb
          subPath: application.rb
        - name: redmine-files
          mountPath: /usr/src/redmine
        - name: redmine-repo
          mountPath: /repositories
        - name: redmine-books
          mountPath: /books
      volumes:
        - name: redmine-config
          configMap:
            name: redmine-config
        - name: redmine-files
          persistentVolumeClaim:
            claimName: redmine-files-pvc
        - name: redmine-repo
          persistentVolumeClaim:
            claimName: redmine-repo-pvc
        - name: redmine-books
          persistentVolumeClaim:
            claimName: redmine-books-pvc

