apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      namespace: production
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: asofainy/redmine:ci
        imagePullPolicy: Always        
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: RAILS_ENV
          value: production
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: redmine-config
          mountPath: /usr/src/redmine/config/configuration.yml
          subPath: configuration.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/database.yml
          subPath: database.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/settings.yml
          subPath: settings.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/application.rb
          subPath: application.rb
        - name: redmine-config
          mountPath: /opt/toolbox/config/env.yml
          subPath: env.yml
        - name: redmine-files
          mountPath: /usr/src/redmine
        - name: redmine-repo
          mountPath: /repositories
        - name: redmine-books
          mountPath: /books
      volumes:
        - name: redmine-config
          configMap:
            name: redmine-config
        - name: redmine-files
          persistentVolumeClaim:
            claimName: redmine-files-pvc
        - name: redmine-repo
          persistentVolumeClaim:
            claimName: redmine-repo-pvc
        - name: redmine-books
          persistentVolumeClaim:
            claimName: redmine-books-pvc

