gitops:
  manifest_projects:
  - id: gitlab-instance-69044ebd/calibre-web
    default_namespace: gitops
    paths:
      # Read all YAML files from this directory.
    - glob: '/deployment/**/*.yaml'
      # Read all .yaml files from team2/apps and all subdirectories.
    reconcile_timeout: 3600s
    dry_run_strategy: none
    prune: true
    prune_timeout: 3600s
    prune_propagation_policy: foreground
    inventory_policy: must_match