apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: calibre-web-loadbalancer-http
spec:
  type: LoadBalancer
  loadBalancerIP: 34.175.159.251
  selector:
    app: calibre-web
  ports:
  - port: 8083
    targetPort: 8083
