apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: redmine-loadbalancer-http
spec:
  type: LoadBalancer
  loadBalancerIP: 34.175.159.251
  selector:
    app: redmine
  ports:
  - port: 3000
    targetPort: 3000
