apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: production
  name: backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: redmine-sa
          containers:
          - name: backup
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: app
                value: redmine
              - name: host
                value: mysql.production.svc.cluster.local
              - name: database
                value: redmine
              - name: username
                value: root
              - name: MYSQL_PWD
                value: My5QL_p@55
              - name: file
                value: dump_`date +'%Y%m%d_%H%M%S'`.sql.gz
            command:
            - /bin/bash
            - -c
            - pod=$(kubectl get pods -n default -l app=mysql --field-selector status.phase=Running | cut -f1 -d ' ' | tail -n 1 ) ; echo $pod ; kubectl exec $pod --namespace default -c mysql -- /bin/bash -c "mkdir -p /backup/$app ; MYSQL_PWD=$MYSQL_PWD mysqldump -h $host -u  $username --routines --triggers $database | gzip -c > /backup/$app/$file ; echo Dump created $file ; ls -ltrah /backup/$app"
          restartPolicy: OnFailure