apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: production
  name: sync-library
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: redmine-sa
          containers:
          - name: sync-library
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - pod=$(kubectl get pods -n production -l app=apollo --field-selector status.phase=Running | cut -f1 -d ' ' | tail -n 1 ) ; echo $pod ; kubectl exec $pod --namespace production -c redmine -- /opt/buildbox/scripts/sync-library.sh
          restartPolicy: OnFailure