gitops:
  manifest_projects:
  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: gitlab-agent
    paths:
    - glob: '/infra/*.yaml'
    
ci_access:
  projects:
    - id: gitlab-instance-69044ebd/ga4k
