apiVersion: v1
kind: ServiceAccount
metadata:
  name: redmine-sa
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: "ClusterRole"
metadata:
  name: redmine-sa
  namespace: production
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: "ClusterRoleBinding"
metadata:
  name: redmine-sa
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "ClusterRole"
  name: redmine-sa
subjects:
- kind: ServiceAccount
  name: redmine-sa
  namespace: production
