apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: redmine-cw-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 34.175.159.251
  selector:
    app: redmine-cw
  ports:
  - name: http-redmine
    port: 3000
    targetPort: 3000
  - name: http-calibre-web
    port: 8083
    targetPort: 8083