apiVersion: v1
kind: Service
metadata:
  resourceVersion: "1"
  name: calibre-web-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: calibre-web