apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-repo-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
