apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner-shell-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner-shell-docker
  template:
    metadata:
      labels:
        app: gitlab-runner-shell-docker
    spec:
#      serviceAccountName: gitlab-runner-admin
      containers:
      - name: gitlab-runner-shell-docker
        image: docker
        securityContext:
          privileged: true
        command: ["/bin/sh","-c"]
        args:
          - apk add bash git gitlab-runner ; 
            token=$(grep registration_token /etc/gitlab/gitlab.rb | cut -d " " -f 4 | tr -d '"') ;
            cmd=$(echo gitlab-runner -l debug register --non-interactive --url http://gitlab-service.production.svc.cluster.local --registration-token $token --executor shell --name $HOSTNAME --tag-list runner-shell-docker ) ;
            $cmd ;
            while [ $? -ne 0 ]; do sleep 60; $cmd ; done ;
            gitlab-runner verify ; 
            gitlab-runner run
        volumeMounts:
        - name: socket
          mountPath: /var/run/docker.sock

        - name: gitlab-config
          mountPath: /etc/gitlab/gitlab.rb
          subPath: gitlab.rb

      volumes:
        - name: socket
          hostPath:
            path: /var/run/docker.sock

        - name: gitlab-config
          configMap:
            name: gitlab-config