apiVersion: v1
kind: Service
metadata:
  name: gitlab-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 34.170.165.32
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gitlab