apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner-docker
  template:
    metadata:
      labels:
        app: gitlab-runner-docker
    spec:
#      serviceAccountName: gitlab-runner-admin
      containers:
      - name: gitlab-runner-docker
        image: gitlab/gitlab-runner
        securityContext:
          privileged: true
        command: ["/bin/sh","-c",]
        args:
          - token=$(grep registration_token /etc/gitlab/gitlab.rb | cut -d " " -f 4 | tr -d '"') ;
            cmd=$(echo gitlab-runner -l debug register --non-interactive --url http://gitlab-service.production.svc.cluster.local --registration-token $token --executor docker --docker-image alpine --name $HOSTNAME --docker-pull-policy always --locked=false --run-untagged=false --docker-privileged=true --limit 0 --tag-list runner-docker ); 
            $cmd ;
            while [ $? -ne 0 ]; do sleep 60; $cmd ; done ;
            gitlab-runner verify ; 
            gitlab-runner run
        volumeMounts:
        - name: socket
          mountPath: /var/run/docker.sock

        - name: gitlab-config
          mountPath: /etc/gitlab/gitlab.rb
          subPath: gitlab.rb

        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "75m"

      volumes:
        - name: socket
          hostPath:
            path: /var/run/docker.sock

        - name: gitlab-config
          configMap:
            name: gitlab-config