apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
#      serviceAccountName: gitlab-runner-admin
      containers:

      - name: gitlab
        image: gitlab/gitlab-ee
        ports:
        - containerPort: 80
#            tail -f /dev/null  
        volumeMounts:
        - name: gitlab-data
          mountPath: /var/opt/gitlab    
        - name: gitlab-config-persistent
          mountPath: /etc/gitlab
        - name: gitlab-config
          mountPath: /etc/gitlab/gitlab.rb
          subPath: gitlab.rb
        - name: gitlab-backup
          mountPath: /backup
          
        resources:
          requests:
            memory: "5Gi"
            cpu: "250m"
          limits:
            memory: "7Gi"
            cpu: "500m"

      volumes:
        - name: gitlab-config
          configMap:
            name: gitlab-config

        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data-pvc

        - name: gitlab-config-persistent
          persistentVolumeClaim:
            claimName: gitlab-config-pvc

        - name: gitlab-backup
          persistentVolumeClaim:
            claimName: gitlab-backup-pvc

        - name: socket
          hostPath:
            path: /var/run/docker.sock


