apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: books-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
