apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: iredmail-loadbalancer-smtps
spec:
  type: LoadBalancer
  loadBalancerIP: 34.175.159.251
  selector:
    app: iredmail
  ports:
  - port: 587
    targetPort: 587
