apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: redmine-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: redmine