apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: mysql-data-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
