apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: gitlab
  name: gitlab-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitlab-runner-admin
          containers:
          - name: gitlab-backup
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - pod=$(kubectl get pods -n gitlab -l app=gitlab --field-selector status.phase=Running | cut -f1 -d ' ' | tail -n 1 ) ; echo "===== Start of job =====" ; kubectl exec $pod --namespace gitlab -c gitlab -- /backup/backup.sh ; echo "===== End of job =====" 
          restartPolicy: OnFailure