apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: gitlab-config-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
