apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iredmail-pvc-imapsieve
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
