apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitlab
  name: gitlab-runner-shell-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner-shell-docker
  template:
    metadata:
      namespace: gitlab
      labels:
        app: gitlab-runner-shell-docker
    spec:
      containers:
      - name: gitlab-runner-shell-docker
        image: docker
        env:
          - name: TOKEN
            value: kEtSzsjQKqS4n4kS3GWT
        securityContext:
          privileged: true
        volumeMounts:
        - name: socket
          mountPath: /var/run/docker.sock
        command:
          - /bin/sh
          - -c
          - "apk add bash git gitlab-runner ; gitlab-runner -l debug register --non-interactive --url http://gitlab-service.gitlab.svc.cluster.local --registration-token ${TOKEN} --executor shell --name $HOSTNAME --tag-list runner-shell-docker ; gitlab-runner verify ; gitlab-runner run"
      volumes:
        - name: socket
          hostPath:
            path: /var/run/docker.sock

    