gitops:
  manifest_projects:
  - id: gitlab-instance-69044ebd/ga4k/agent-smith
    default_namespace: default
    paths:
      # Read all YAML files from this directory.
    - glob: 'calibre-web/deployment/**/*.yaml'
      # Read all .yaml files from team2/apps and all subdirectories.
    reconcile_timeout: 3600s
    dry_run_strategy: none
    prune: true
    prune_timeout: 3600s
    prune_propagation_policy: foreground
    inventory_policy: must_match