gitops:
  manifest_projects:
  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: default
    paths:
    - glob: '/deploy/default/**/*.yaml'
    reconcile_timeout: 3600s
    dry_run_strategy: none
    prune: true
    prune_timeout: 3600s
    prune_propagation_policy: foreground
    inventory_policy: must_match
    
  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: test
    paths:
    - glob: '/deploy/test/**/*.yaml'

  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: test
    paths:
    - glob: '/deploy/production/**/*.yaml'

observability:
  logging:
    level: debug
    grpc_level: warning