#https://docs.gitlab.com/ee/user/clusters/agent/gitops.html#gitops-configuration-reference

gitops:
  manifest_projects:
  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: default
    paths:
    - glob: '/default/**/*.yaml'
    - glob: '/test/**/*.yaml'
    - glob: '/production/**/*.yaml'

observability:
  logging:
    level: debug
    grpc_level: warning