#https://docs.gitlab.com/ee/user/clusters/agent/gitops.html#gitops-configuration-reference
gitops:
  manifest_projects:
  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: test
    paths:
    - glob: '/deploy/default/**/*.yaml'
  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: production
    paths:
    - glob: '/deploy/production/**/*.yaml'
  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: test
    paths:
    - glob: '/deploy/test/**/*.yaml'
    reconcile_timeout: 3600s
    dry_run_strategy: none
    prune: true
    prune_timeout: 3600s
    prune_propagation_policy: foreground
    inventory_policy: must_match
observability:
  logging:
    level: debug
    grpc_level: warning
