gitops:
  manifest_projects:
  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: default
    paths:
    - glob: '/default/**/*.yaml'
  
  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: test
    paths:
    - glob: '/test/**/*.yaml'

  - id: gitlab-instance-69044ebd/ga4k
    default_namespace: test
    paths:
    - glob: '/production/**/*.yaml'

observability:
  logging:
    level: debug
    grpc_level: warning