apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-config-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
