apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      namespace: production
      labels:
        app: apollo
    spec:
      containers:
      - name: redmine
        image: asofainy/redmine:latest
        imagePullPolicy: Always        
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: RAILS_ENV
          value: production
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: redmine-config
          mountPath: /usr/src/redmine/config/configuration.yml
          subPath: configuration.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/database.yml
          subPath: database.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/settings.yml
          subPath: settings.yml
        - name: redmine-config
          mountPath: /usr/src/redmine/config/application.rb
          subPath: application.rb
        - name: redmine-config
          mountPath: /config/env.yml
          subPath: env.yml
        - name: redmine-files
          mountPath: /usr/src/redmine
        - name: repo
          mountPath: /repositories
        - name: library
          mountPath: /library
      - name: calibre-web
        image: asofainy/calibre-web:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "50m"
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: library
          mountPath: /library
      volumes:
        - name: repo
          persistentVolumeClaim:
            claimName: repo-pvc
        - name: library
          persistentVolumeClaim:
            claimName: library-pvc
        - name: redmine-config
          configMap:
            name: redmine-config
        - name: redmine-files
          persistentVolumeClaim:
            claimName: redmine-files-pvc
        - name: calibre-web-data
          persistentVolumeClaim:
            claimName: calibre-web-data-pvc
