
# https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/57e026d7f43f63adc32cdd2b21e6d450abcf0686/values.yaml#L490-500

replicas: 2

rbac:
  create: false
  serviceAccountName: gitlab-runner-admin

gitlabUrl: http://gitlab-service.gitlab.svc.cluster.local
runnerRegistrationToken: kEtSzsjQKqS4n4kS3GWT

runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        image = "ubuntu:16.04"
        service_account = "gitlab-runner-admin"
        allowed_pull_policies = ["always", "if-not-present"]

  tags: "runner-kubernetes"