apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: iredmail-mysql-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: iredmail-mail-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi   
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: iredmail-pvc-backup-mysql
#spec:
#  storageClassName: custom
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: iredmail-pvc-clamav
#spec:
#  storageClassName: custom
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: iredmail-pvc-custom
# spec:
#   storageClassName: custom
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: iredmail-pvc-imapsieve
# spec:
#   storageClassName: custom
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: iredmail-pvc-mailboxes
# spec:
#   storageClassName: custom
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: iredmail-pvc-mlmmj-archive
# spec:
#   storageClassName: custom
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: iredmail-pvc-mlmmj
# spec:
#   storageClassName: custom
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: iredmail-pvc-postfix-queue
# spec:
#   storageClassName: custom
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: iredmail-pvc-spamassassin
# spec:
#   storageClassName: custom
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: iredmail-pvc-ssl
# spec:
#   storageClassName: custom
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi