apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  namespace: production
  name: calibre-web-data-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Ki
