apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitlab
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      namespace: gitlab
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ee
        resources:
          requests:
            memory: "5Gi"
            cpu: "1000m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: gitlab-data
          mountPath: /var/opt/gitlab
        - name: gitlab-config
          mountPath: /etc/gitlab/gitlab.rb
          subPath: gitlab.rb
        - name: gitlab-config-persistent
          mountPath: /etc/gitlab
        - name: gitlab-backup
          mountPath: /backup
      volumes:
        - name: gitlab-config
          configMap:
            name: gitlab-config
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data-pvc
        - name: gitlab-config-persistent
          persistentVolumeClaim:
            claimName: gitlab-config-pvc

        - name: gitlab-backup
          persistentVolumeClaim:
            claimName: gitlab-backup-pvc
