apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-data-pvc
spec:
  storageClassName: custom
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
